[platformio]
src_dir = .

[env:teensy41]
platform = platformio/teensy@5.2.0
board = teensy41
framework = arduino
lib_deps =
    ILI9341_T4=https://github.com/open-control/ILI9341_T4.git#95be8e9487442230d9bcb45d23ffba72f6070c85
build_src_filter = +<main.cpp>
